on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 16 * *"

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2

      - name: Run R script
        run: Rscript script.R

