on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 16 * *"

name: R-CMD-check

jobs:
  R-CMD-check:
    strategy:
      fail-fast: false
      matrix:
        include:
          - install_pureseqtm: "true" 
          - install_pureseqtm: "false"

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install libgit2-dev
        run: sudo apt install -qq libgit2-dev

      - name: Install libcurl4-openssl-dev
        run: sudo apt install -qq libcurl4-openssl-dev

      - name: Install libharfbuzz-dev libfribidi-dev
        run: sudo apt install -qq libharfbuzz-dev libfribidi-dev

      #- name: Install dependencies
      #  run: |
      #    remotes::install_github("richelbilderbeek/pureseqtmrinstall")
      #    remotes::install_github("richelbilderbeek/pureseqtmr")
      #  shell: Rscript {0}

      - name: Report
        run: Rscript script.R

